### ISSUE TITLE
Automate assignment of the certificate in macOS Server App

### ISSUE THREAD

**Issue by opus-nbonenberger** [pixelchrome/macoscertbot#1]
> To use this certificate:
> 
> Go to Secure services using > select Custom... > and select for the Profile Manager the Letsencrypt certificate
> 
> Now you need to restart the Profile Manager

Can this be automated with a script?

**Comment by pixelchrome** [comment]
Currently I have no script available to automate this. Maybe in a future release.

Do you have some input for such a script?

**Comment by opus-nbonenberger** [comment]
Well, the input should be the created and imported certificate. I am far from being an expert in scripting, sorry. The whole process of requesting and issuing a certificate is automated, so it would be nice to have the part of selecting it in macOS server App automated.

**Comment by pixelchrome** [comment]
# Apple has discontinued macOS Server https://support.apple.com/en-us/HT208312

Repo is being archived...
